# Generated by Django 4.0.2 on 2022-02-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='email',
            name='email_message',
        ),
        migrations.AddField(
            model_name='email',
            name='message',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
