# Generated by Django 4.0.2 on 2022-02-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='name',
            new_name='Customer_name',
        ),
    ]
