# Generated by Django 4.0.2 on 2022-02-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_name_checkout_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='Customer_name',
            new_name='name',
        ),
    ]
