# Generated by Django 4.0.2 on 2022-02-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_customer_name_checkout_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='items_json',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
